name: PHP Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['7.4', '8.0', '8.1']
    name: PHP ${{ matrix.php-version }} Unit Tests

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, json, curl, fileinfo
          coverage: none

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - uses: actions/checkout@v4

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run Unit Tests
        run: composer run-script test-unit

      - name: Static Analyse
        run: composer run-script analyse

  feature-tests:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        php-version: ['7.4', '8.0', '8.1']
    name: PHP ${{ matrix.php-version }} Feature Tests
    env:
      BLUESKY_IDENTIFIER: ${{ secrets.BLUESKY_IDENTIFIER }}
      BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, json, curl, fileinfo
          coverage: none

      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run Feature Tests
        run: composer run-script test-feature